server:
  port: 8081
  error:
    whitelabel:
      enabled: true
    path: /error

logging:
  level:
    ROOT: DEBUG
    org:
      springframework:
        security: debug

#https://medium.com/devops-dudes/securing-spring-boot-rest-apis-with-keycloak-1d760b2004e
keycloak:
  #the keycloak authentication url
  #keycloack has to have a confidential client for protecting this MS
  auth-server-url: http://CHANGE-IT/auth
  ssl-required: none
  bearer-only: true
  credentials:
    #the client must be confidential, this is the secret
    secret: CHANGE-IT
  realm: CHANGE-IT
  #the client name
  resource: CHANGE-IT
  use-resource-role-mappings: true

#the configuration for open api
app:
  version: 1
  name: springboot-kc-sample
  security:
    auth-server-url: ${keycloak.auth-server-url}
    realm: ${keycloak.realm}
    client-ui: entando-web
