
entando:
  spring.security.oauth2.client.registration.oidc.client.secret: ${spring.security.oauth2.client.registration.oidc.client.secret:""}
  keycloak.public.client.id:  ${keycloak.public.client.id:""}
  keycloak.auth.url: ${keycloak.auth.url:""}
  keycloak.client.id: ${keycloak.client.id:""}
  keycloak.realm: ${keycloak.realm:""}

server:
  port: 8081
  error:
    whitelabel:
      enabled: true
    path: /error

logging:
  level:
    ROOT: DEBUG
    org:
      springframework:
        security: debug

#https://medium.com/devops-dudes/securing-spring-boot-rest-apis-with-keycloak-1d760b2004e
keycloak:
  auth-server-url: ${entando.keycloak.auth.url}
  bearer-only: true
  credentials:
    secret: ${entando.spring.security.oauth2.client.registration.oidc.client.secret}
  resource: ${entando.keycloak.client.id}
  #realm: ${entando.keycloak.realm} #from env
  use-resource-role-mappings: true

app:
  version: 1
  name: springboot-kc-sample
  security:
    auth-server-url: ${entando.keycloak.auth.url}
    realm: ${entando.keycloak.realm}
    client-ui: ${entando.keycloak.public.client.id}
